include ./nord.conf

font_family       MesloLGS Nerd Font Mono
font_size 16.0
disable_ligatures never
scrollback_lines 10000

tab_bar_style slant
tab_title_template "[{index-1}] {title}"

allow_hyperlinks yes
shell_integration enabled

# § as leader key (splits/tabs)
map §>c combine : goto_layout splits : new_tab
map §>C combine : goto_layout splits : new_tab_with_cwd !neighbor
map §>. move_tab_forward
map §>, move_tab_backward

map §>0 goto_tab 1
map §>1 goto_tab 2
map §>2 goto_tab 3
map §>3 goto_tab 4
map §>4 goto_tab 5
map §>5 goto_tab 6
map §>6 goto_tab 7
map §>7 goto_tab 8
map §>8 goto_tab 9
map §>9 goto_tab 10

map §>z toggle_layout stack
map §>space goto_layout splits
map §>s combine : goto_layout splits : launch --location=hsplit --cwd=current
map §>v combine : goto_layout splits : launch --location=vsplit --cwd=current
map §>l neighboring_window right
map §>h neighboring_window left
map §>k neighboring_window top
map §>j neighboring_window bottom
